"""Generate realistic TCR CDR3 sequences with OLGA (test-only dependency).

OLGA is used solely to produce biologically plausible sequences for tests; the
library itself never imports it. Tests skip gracefully when OLGA is unavailable.
"""
import csv
import functools
import os
import shutil
import subprocess
import sys
import tempfile

import pytest


def _olga_cli():
    # Prefer the script next to the running interpreter (venv may not be on PATH).
    cand = os.path.join(os.path.dirname(sys.executable), "olga-generate_sequences")
    if os.path.exists(cand):
        return cand
    return shutil.which("olga-generate_sequences")


def olga_available():
    return _olga_cli() is not None


@functools.lru_cache(maxsize=8)
def generate(n=200, chain="humanTRB"):
    """Return a list of (nt, aa) CDR3 tuples generated by OLGA.

    Skips the calling test if OLGA is missing or fails to run.
    """
    cli = _olga_cli()
    if cli is None:
        pytest.skip("OLGA not installed (pip install olga)")
    out = os.path.join(tempfile.mkdtemp(), "olga.tsv")  # must not pre-exist (OLGA won't overwrite)
    try:
        subprocess.run(
            [cli, f"--{chain}", "-n", str(n), "-o", out],
            check=True, capture_output=True, timeout=300,
        )
    except (subprocess.CalledProcessError, subprocess.TimeoutExpired) as e:  # pragma: no cover
        pytest.skip(f"OLGA generation failed: {e}")
    seqs = []
    with open(out) as fh:
        for row in csv.reader(fh, delimiter="\t"):
            if len(row) >= 2 and row[0] and row[1]:
                seqs.append((row[0].upper(), row[1].upper()))
    if not seqs:  # pragma: no cover
        pytest.skip("OLGA produced no sequences")
    return seqs
